# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impute_NA <- function(na, i_index, j_index, ymat, tau_yes, tau_no, beta, kappa, n) {
    .Call(`_SLFM1D_impute_NA`, na, i_index, j_index, ymat, tau_yes, tau_no, beta, kappa, n)
}

update_beta <- function(t, nr_par, epsilon_vec, epsilon2_vec, leap_vec, nc, omega, cbeta_prior, beta, tau_yes, tau_no, kappa, ymat) {
    .Call(`_SLFM1D_update_beta`, t, nr_par, epsilon_vec, epsilon2_vec, leap_vec, nc, omega, cbeta_prior, beta, tau_yes, tau_no, kappa, ymat)
}

update_tau_yes <- function(t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call(`_SLFM1D_update_tau_yes`, t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, tau_yes, tau_no, kappa, ymat)
}

update_tau_no <- function(t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, yes_out, tau_no, kappa, ymat) {
    .Call(`_SLFM1D_update_tau_no`, t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, yes_out, tau_no, kappa, ymat)
}

update_omega <- function(omega, beta, nr, a, b, omega_sd) {
    .Call(`_SLFM1D_update_omega`, omega, beta, nr, a, b, omega_sd)
}

update_kappa <- function(t, nc_par, nr, beta, yes_out, no_out, kappa, ymat, kappa_a, ccc, t_sig_vec) {
    .Call(`_SLFM1D_update_kappa`, t, nc_par, nr, beta, yes_out, no_out, kappa, ymat, kappa_a, ccc, t_sig_vec)
}

waic_cpp <- function(t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call(`_SLFM1D_waic_cpp`, t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat)
}

predict <- function(t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call(`_SLFM1D_predict`, t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat)
}

