# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@useDynLib SLFM1D
#'@export
impute_NA <- function(na, i_index, j_index, ymat, tau_yes, tau_no, beta, kappa, n) {
    .Call('_SLFM1D_impute_NA', PACKAGE = 'SLFM1D', na, i_index, j_index, ymat, tau_yes, tau_no, beta, kappa, n)
}

#'@useDynLib SLFM1D
#'@export
update_beta <- function(t, nr_par, epsilon_vec, epsilon2_vec, leap_vec, nc, omega, cbeta_prior, beta, tau_yes, tau_no, kappa, ymat) {
    .Call('_SLFM1D_update_beta', PACKAGE = 'SLFM1D', t, nr_par, epsilon_vec, epsilon2_vec, leap_vec, nc, omega, cbeta_prior, beta, tau_yes, tau_no, kappa, ymat)
}

#'@useDynLib SLFM1D
#'@export
update_tau_yes <- function(t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call('_SLFM1D_update_tau_yes', PACKAGE = 'SLFM1D', t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, tau_yes, tau_no, kappa, ymat)
}

#'@useDynLib SLFM1D
#'@export
update_tau_no <- function(t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, yes_out, tau_no, kappa, ymat) {
    .Call('_SLFM1D_update_tau_no', PACKAGE = 'SLFM1D', t, nc_par, epsilon_vec, epsilon2_vec, leap_vec, nr, beta, yes_out, tau_no, kappa, ymat)
}

#'@useDynLib SLFM1D
#'@export
update_omega <- function(omega, beta, nr, a, b, omega_sd) {
    .Call('_SLFM1D_update_omega', PACKAGE = 'SLFM1D', omega, beta, nr, a, b, omega_sd)
}

#'@useDynLib SLFM1D
#'@export
update_kappa <- function(t, nc_par, nr, beta, yes_out, no_out, kappa, ymat, kappa_a, ccc, t_sig_vec) {
    .Call('_SLFM1D_update_kappa', PACKAGE = 'SLFM1D', t, nc_par, nr, beta, yes_out, no_out, kappa, ymat, kappa_a, ccc, t_sig_vec)
}

#'@useDynLib SLFM1D
#'@export
waic_cpp <- function(t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call('_SLFM1D_waic_cpp', PACKAGE = 'SLFM1D', t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat)
}

#'@useDynLib SLFM1D
#'@export
predict <- function(t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat) {
    .Call('_SLFM1D_predict', PACKAGE = 'SLFM1D', t, nc_par, nr, beta, tau_yes, tau_no, kappa, ymat)
}

